### ISSUE TITLE
Audit RSBlocks, move still-used things to Blocks.swift

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/RSCore#19]
RSBlocks is Objective-C. Anything we’re still using in NetNewsWire from RSBlocks should be ported to Swift and moved to Blocks.swift.

And then RSBlocks.h and .m should be deleted.

**Comment by Wevah** [comment]
I can't find anything in RSBlocks that's ultimately used anywhere in NetNewsWire, unless I'm missing something. (Of course, I converted everything before checking…)
