### ISSUE TITLE
MainThreadOperation and MainThreadOperationQueue in Objective-c?

### ISSUE THREAD

**Issue by inPhilly** [Ranchero-Software/RSCore#57]
I know nobody uses Objective-c anymore, but I have an old app. Is there anyway I can use MainThreadOperation and MainThreadOperationQueue in my app? I think they are exactly what I need right now. Thank you.

**Comment by brentsimmons** [comment]
In theory you could write an Objective-C friendly wrapper in Swift to bridge the two worlds.

**Comment by inPhilly** [comment]
I don't know Swift, I only have this one old app. Thank you though. Your code looks amazing and maybe one day I can use it.
